include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - flutter/**
    - build/**
    - .dart_tool/**
    - ios/Pods/**
    - macos/Pods/**
    - lib/features/_disabled_experimental/**
    - lib/_quarantine/**
