name: flow_ai
description: "Flow Ai - AI-Powered Menstrual Health platform with advanced machine learning predictions, intelligent insights, and personalized health analytics."
publish_to: 'none'

version: 2.1.2+11

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^13.2.4
  
  # UI Components
  flutter_animate: ^4.2.0
  lottie: ^3.0.0
  
  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  
  # Data Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # AI & Analytics
  ml_linalg: ^13.0.0
  tflite_flutter: ^0.10.4
  
  # Notifications
  flutter_local_notifications: ^17.2.4
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # HTTP & API
  http: ^1.1.0
  
  # URL Launcher
  url_launcher: ^6.3.2
  
  # Device Info
  device_info_plus: ^9.1.1
  
  # Network Connectivity
  connectivity_plus: ^5.0.2
  
  # Biometric Authentication
  local_auth: ^2.1.7
  
  # Health Data Integration
  health: ^13.1.4
  
  # OAuth Authentication  
  # Temporarily disabled for iOS compatibility
  # google_sign_in: 6.1.6
  sign_in_with_apple: ^7.0.1
  # firebase_auth: ^5.3.1     # Temporarily disabled for iOS build fix
  # firebase_core: ^3.8.0     # Temporarily disabled for iOS build fix
  
  # State Persistence
  hydrated_bloc: ^9.1.2
  
  # Chat UI Components
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  
  # UUID Generation
  uuid: ^4.2.1
  
  # Cloud Firestore
  # cloud_firestore: ^5.4.4  # Temporarily disabled for iOS build fix
  
  # Crypto
  crypto: ^3.0.3
  
  # Encrypt
  encrypt: ^5.0.1
  
  # PDF
  pdf: ^3.10.7
  
  # CSV
  csv: ^5.0.2
  
  # File Picker
  file_picker: ^8.0.7
  
  # Share Plus
  share_plus: ^7.2.1
  
  # Permission Handler
  permission_handler: ^11.1.0
  
  # Local Auth Platform Interface
  local_auth_platform_interface: ^1.0.8
  
  # Advertising
  google_mobile_ads: ^5.1.0
  
  # In-App Purchases (Premium Subscriptions)
  in_app_purchase: ^3.1.11
  in_app_purchase_android: ^0.3.3+1
  in_app_purchase_storekit: ^0.3.9+2
  
  # Platform utilities (override to fix deprecated API issue)
  platform: ^3.1.0
  
  # Cross-platform compatibility
  package_info_plus: ^4.2.0
  
  # Additional Firebase services
  # firebase_analytics: ^11.3.3   # Temporarily disabled for iOS build fix
  # firebase_crashlytics: ^4.1.3  # Temporarily disabled for iOS build fix
  # firebase_messaging: ^15.1.3   # Temporarily disabled for iOS build fix
  
  # Additional mobile features
  image_picker: ^1.0.4
  # camera: ^0.10.5+5  # Temporarily disabled for iOS build
  geolocator: ^10.1.0
  vibration: ^3.1.3
  
  # Web-specific dependencies
  # firebase_auth_web: ^5.14.1  # Temporarily disabled for iOS build
  
  # Logging
  logger: ^2.0.2+1
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # Archive (for data export/import compression)
  archive: ^3.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    
  # Mocking for unit tests
  mockito: ^5.4.4
  build_runner: ^2.4.12
  json_serializable: ^6.7.1
    
  # App icon generation
  flutter_launcher_icons: ^0.14.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # Internationalization support
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/brand/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "flow_ai_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "flow_ai_icon.png"
    background_color: "#4F46E5"
    theme_color: "#C147E9"
  windows:
    generate: true
    image_path: "flow_ai_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "flow_ai_icon.png"
