// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUex6NhYiUsxZ7-cTzO6QNCOnFyfx9IQo',
    appId: '1:752724279049:android:cbdbf2519e6167a50d1dd8',
    messagingSenderId: '752724279049',
    projectId: 'flow-ai-656b3',
    storageBucket: 'flow-ai-656b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_1tl3UOeIKMjPdYLk_FtD65Dqe8m-27A',
    appId: '1:752724279049:ios:196dbadf2a6d76a80d1dd8',
    messagingSenderId: '752724279049',
    projectId: 'flow-ai-656b3',
    storageBucket: 'flow-ai-656b3.firebasestorage.app',
    iosClientId: '752724279049-ei2380bh9o9ph6tq348lht6sf0ks52n2.apps.googleusercontent.com',
    iosBundleId: 'com.flowai.health',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMf0arbNCzW_ZAei9a4qGZIj3NyFwPXks',
    appId: '1:752724279049:web:884c1adca145732d0d1dd8',
    messagingSenderId: '752724279049',
    projectId: 'flow-ai-656b3',
    authDomain: 'flow-ai-656b3.firebaseapp.com',
    storageBucket: 'flow-ai-656b3.firebasestorage.app',
    measurementId: 'G-5XZ9JNL898',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_1tl3UOeIKMjPdYLk_FtD65Dqe8m-27A',
    appId: '1:752724279049:ios:d9b610947a791a8b0d1dd8',
    messagingSenderId: '752724279049',
    projectId: 'flow-ai-656b3',
    storageBucket: 'flow-ai-656b3.firebasestorage.app',
    iosClientId: '752724279049-r7janjmcp2uehkg8qvrvjae9qlu8jsq2.apps.googleusercontent.com',
    iosBundleId: 'com.flowai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMf0arbNCzW_ZAei9a4qGZIj3NyFwPXks',
    appId: '1:752724279049:web:f661a3bd8f87efd70d1dd8',
    messagingSenderId: '752724279049',
    projectId: 'flow-ai-656b3',
    authDomain: 'flow-ai-656b3.firebaseapp.com',
    storageBucket: 'flow-ai-656b3.firebasestorage.app',
    measurementId: 'G-1X098QTRYG',
  );

}