source 'https://cdn.cocoapods.org/'
platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings.delete('SDKROOT')
      config.build_settings['GCC_C_LANGUAGE_STANDARD'] = 'compiler-default'
      config.build_settings['GCC_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings.delete('OTHER_CPLUSPLUSFLAGS')

      if config.build_settings['OTHER_CFLAGS']
        flags = config.build_settings['OTHER_CFLAGS']
        if flags.is_a?(Array)
          flags = flags.reject { |f| f == '-x' || f == 'c' || f == '-x c' }
          config.build_settings['OTHER_CFLAGS'] = flags
        else
          config.build_settings['OTHER_CFLAGS'] = flags.to_s.gsub('-x c', '')
        end
      end

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'COCOAPODS=1'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'arm64 x86_64'
      config.build_settings['ARCHS[sdk=iphoneos*]'] = 'arm64'
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphoneos*]')
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'

      if target.name == 'leveldb-library'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'LEVELDB_PLATFORM_POSIX=1'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= []
        config.build_settings['HEADER_SEARCH_PATHS'] << '$(PODS_TARGET_SRCROOT)'
      end

      if target.respond_to?(:product_type) && target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end

      if target.name.include?("GoogleDataTransport") || target.name.include?("nanopb") || target.name.include?("FirebaseFirestore")
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PB_FIELD_32BIT=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PB_FIELD_16BIT=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PB_NO_PACKED_STRUCTS=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PB_ENABLE_MALLOC=1'
      end

      if target.name.include?("Firebase")
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'Firebase_VERSION=11.15.0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FIRFirestore_VERSION=11.15.0'
      end

      if target.name == 'GoogleSignIn'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GID_SDK_VERSION=8.0.0'
      end
    end
  end
end
